# /* wallust template - colors-kitty */

foreground         #DBDAD8
background         #1F1F1F
cursor             #888886

active_tab_foreground     #1F1F1F
active_tab_background     #DBDAD8
inactive_tab_foreground   #DBDAD8
inactive_tab_background   #1F1F1F

active_border_color   #DBDAD8
inactive_border_color #1F1F1F
bell_border_color     #181717

color0      #464545
color1		#181717
color2		#282828
color3		#2D2D2C
color4		#474646
color5		#565452
color6		#716F6C
color7		#C2C1BF
color8		#888786
color9		#201F1F
color10		#363635
color11		#3C3B3A
color12		#5F5E5E
color13		#73716E
color14		#979490
color15		#C2C1BF
