# /* wallust template - colors-kitty */

foreground         #BFCAD3
background         #17181A
cursor             #68727A

active_tab_foreground     #17181A
active_tab_background     #BFCAD3
inactive_tab_foreground   #BFCAD3
inactive_tab_background   #17181A

active_border_color   #BFCAD3
inactive_border_color #17181A
bell_border_color     #0D1319

color0      #3E3F41
color1		#0D1319
color2		#0D1319
color3		#0F161D
color4		#10171E
color5		#2E4253
color6		#364D61
color7		#9BABB8
color8		#6C7780
color9		#111921
color10		#111921
color11		#141E27
color12		#151F28
color13		#3E586F
color14		#486781
color15		#9BABB8
